'''
删除一组字符中重复的元素，例如aaaaab删除后为b。
输入是多组字符，输出是每一行删除后的元素。若全部删除则输出no
例输入：a
       aaaabbb
输出：a
     no
'''
a=(1,2,3.4,'hello','hello','world',[],(1),{3},'hello')
print(a[::-1])
b=a.index([])
print(b)
c=a.count('hello')
print(c)